### ISSUE TITLE
seleniumrequests.PhantomJS.get() does not use the Selenium driver

### ISSUE THREAD

**Issue by seanthegeek** [cryzed/Selenium-Requests#9] opened 2016-06-29 18:50 UTC
Hello,

I tried the following code with Python 3.5 on Debian Testing:

```
from seleniumrequests import PhantomJS

driver = PhantomJS()
driver.set_window_size(1024, 768)
request = driver.request('GET', 'http://example.com/')
print(request.text)
driver.save_screenshot("example.png")
```
The result seeps to be that the requests module makes the request as usual, instead of usind webdriver. The webdriver returns no content.

**Comment by cryzed** [comment] 2016-06-29 19:11
This is expected behavior: Selenium-Requests can't magically translate a Selenium webdriver "response" (which does not actually conceptually exist) into a requests response.

Selenium-Requests makes a request using the requests library that uses the running webdriver's cookies for that domain and emulates the default HTTP headers sent by that webdriver. The result is a low-level HTTP request and response created with the webdriver's state. This is needed because the Selenium interface is very high-level, and doing much more than opening pages and exploring the DOM is not really possible natively in Python.

If you want to take a screenshot of the website, you have to use the webdriver's `get` method beforehand, because:

> All operations preserve the original state (active window handle and window handles) of the WebDriver

So if a tab or window is opened to get access to the website's cookies through the Selenium interface, it will be closed at the end.

**Comment by cryzed** [comment] 2016-06-30 12:38
I'm closing this, let me know if you disagree.

**Closed by cryzed** 2016-06-30 12:38 UTC
