### ISSUE TITLE
Chrome block on 127.0.0.1:xxxx after request

### ISSUE THREAD

**Issue by cestjordan** [cryzed/Selenium-Requests#33] opened 2019-10-23 12:30 UTC
Hello,

I'm in Python3 , I try on Windows and Debian
I have a trouble, I want to laun request using seleniumrequest with chrome.
But, when I send request, it's work 1/3 times.
when it doesn't work , Chrome open another tab, with url : 127.0.0.1:xxxxx ( random port ) ; and I can't do anything.
I must kill python.
Even with timeout option in my request, it's the same.
It's the same trouble with every request ( post or get )

For example, a very simple request.

from seleniumrequests import Chrome
webdriver=Chrome()
page=webdriver.request('GET','https://www.google.com/')

Sometimes it's work, other time I still block on the tab , and do Nothing…

Have you ever see it ?

Thanks

**Comment by cryzed** [comment] 2020-06-04 14:57
I'm closing this because it's so old now, bit I'm pretty sure it's either your firewall interfering or some Antivirus creating trouble -- this happens when the webserver spawned by Selenium-Requests for the duration of a single request, can't be reached.

**Closed by cryzed** 2020-06-04 14:57 UTC

**Comment by hudcap** [comment] 2020-07-06 20:07
I am having this issue 100% of the time on a computer running Windows 10 64-bit, Python 3.8.3. I disabled the Windows Defender firewall, but it still doesn't work.
On my laptop, running the same, it works.

I tried running `netstat` and it seems the port is being opened, although I'm not entirely sure I understand the output correctly.

Any pointers on where I can look to pinpoint the problem?

**Comment by moritzj29** [comment] 2022-01-10 20:39
I'm also facing this issue and now realized that this library is simply not usable with the `webdriver.Remote` since the spawned HTTP Server must be available at `127.0.0.1`. Obviously, `localhost` is not accessible for the remote WebDriver...

Injecting the correct hostname in the code is a temporary workaround and demonstrates that this is indeed the cause.

Any ideas on how to make this work with remote webdrivers?

Clearly, `Readme.md` should be changed for noobs like me, who think 'any' includes the remote driver:
```
# Import any WebDriver class that you would usually import from
# selenium.webdriver from the seleniumrequests module
```

**Comment by NiBa97** [comment] 2022-02-08 11:11
Im also getting this error too, although im combining it with the undetectable chromedriver. Do you happen to have an idea how to prevent that blocking tab event to occur?

**Comment by hudcap** [comment] 2022-06-01 14:01
When not in headless mode, I might have another "fix."
This line creates the server and listens from all ips (0.0.0.0):
https://github.com/cryzed/Selenium-Requests/blob/70aa2280f26a1335a231a7493225d46703288f75/seleniumrequests/request.py#L59

I couldn't verify anything, but I'd seen comments about issues with listening from 0.0.0.0, so I tried adjusting that line to:
```python
server = http.server.HTTPServer(("127.0.0.1", port), HTTPRequestHandler)
```

For now, it's working, but it's worked on and off in the past, so I'm not certain this is a real solution.
When I look at `netstat`, it still seems to be listening to 0.0.0.0, but I'm already in over my head on this, so I don't know what to make of that.
